package sos.db;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class SOSDB {
  
  final protected String url;
  final protected String username;
  final protected String password;
  
  public SOSDB (String url, String username, String password) {
    this.url = url;
    this.username = username;
    this.password = password; 
  }
  
  protected Connection getConnection() throws SQLException, IOException {
    System.setProperty("jdbc.drivers", "org.apache.derby.jdbc.ClientDriver");
    return DriverManager.getConnection(url, username, password);
  }
  
  protected boolean tableExists (Connection con, String table) {
    int numRows = 0;
    try {
      DatabaseMetaData dbmd = con.getMetaData();
      ResultSet rs = dbmd.getTables(null, "APP", table.toUpperCase(), null);
      while(rs.next()) ++numRows;
    } catch (Exception e) {}
      System.out.println(""+numRows);
    return numRows > 0;
  }
  
  public void createTables(){
    java.sql.Connection conn = null;
    java.sql.Statement stat = null;
    String sql;
    try {
      conn = getConnection();
      stat = conn.createStatement();
      if (!tableExists(conn, "CATEGORY")) {
        sql = "CREATE TABLE Category (\"Category ID\" integer GENERATED BY DEFAULT AS IDENTITY, \"Category Name\" varchar(50) NOT NULL, PRIMARY KEY (\"Category ID\"))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "ITEM")) {
        sql = "CREATE TABLE ITEM ("
                + "ItemNo VARCHAR(5) CONSTRAINT PK_ITEM PRIMARY KEY,"
                + "Name VARCHAR(50), Description VARCHAR(100), Brand VARCHAR(25), "
                + "CatID VARCHAR(5) REFERENCES CATEGORY(CatID), Price INTEGER)";
        stat.execute(sql);
      }
      if (!tableExists(conn, "CLIENT")) {
        sql = "CREATE TABLE Client (ClientID varchar(50) NOT NULL, Password varchar(10) NOT NULL, ClientName varchar(30) NOT NULL, TeleNo integer NOT NULL, Address varchar(50) NOT NULL, Verified smallint NOT NULL, PRIMARY KEY (ClientID))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "CLIENT_ORDER")) {
        sql = "CREATE TABLE CLIENT_ORDER ("
                + "OrdNo VARCHAR(5) CONSTRAINT PK_CLIENT_ORDER PRIMARY KEY,"
                + "Timestamp VARCHAR(20), CID VARCHAR(5) REFERENCES CLIENT(CID))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "GIFT")) {
        sql = "CREATE TABLE Gift (\"Gift ID\" integer GENERATED BY DEFAULT AS IDENTITY, Point integer NOT NULL, \"Gift Name\" varchar(50) NOT NULL, Description varchar(255), \"Order ID\" varchar(10) NOT NULL, PRIMARY KEY (\"Gift ID\"))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "ORDER")) {
        sql = "CREATE TABLE \"Order\" (\"Order ID\" varchar(10) NOT NULL, \"Total Amount\" integer NOT NULL, \"Order Date\" date NOT NULL, \"Order Status\" char(10) NOT NULL, ClientID varchar(50) NOT NULL, PRIMARY KEY (\"Order ID\"))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "PRODUCT")) {
        sql = "CREATE TABLE Product (\"Product ID\" varchar(8) NOT NULL, \"Product Name\" varchar(50) NOT NULL, Price integer NOT NULL, Description varchar(255), \"Category ID\" integer NOT NULL, PRIMARY KEY (\"Product ID\"))";
        stat.execute(sql);
      }
      if (!tableExists(conn, "PRODUCT_ORDER")) {
        sql = "CREATE TABLE Product_Order (Quantity integer NOT NULL, \"Product ID\" varchar(8) NOT NULL, \"Order ID\" varchar(10) NOT NULL);";
        stat.execute(sql);
      }
      //Alter table part
      if(tableExists(conn,"PRODUCT")){
          sql = "ALTER TABLE Product_Order ADD CONSTRAINT FKProduct_Or958232 FOREIGN KEY (\"Order ID\") REFERENCES \"Order\" (\"Order ID\")";
          stat.execute(sql);
      }
      if(tableExists(conn,"PRODUCT")){
          sql = "ALTER TABLE Product_Order ADD CONSTRAINT FKProduct_Or204152 FOREIGN KEY (\"Product ID\") REFERENCES Product (\"Product ID\")";
          stat.execute(sql);
      }
      if(tableExists(conn,"ORDER")){
          sql = "ALTER TABLE \"Order\" ADD CONSTRAINT FKOrder286870 FOREIGN KEY (ClientID) REFERENCES Client (ClientID)";
          stat.execute(sql);
      }
      if(tableExists(conn,"PRODUCT")){
          sql = "ALTER TABLE Product ADD CONSTRAINT FKProduct425245 FOREIGN KEY (\"Category ID\") REFERENCES Category (\"Category ID\")";
          stat.execute(sql);
      }
      if(tableExists(conn,"GIFT")){
          sql = "ALTER TABLE Gift ADD CONSTRAINT FKGift520890 FOREIGN KEY (\"Order ID\") REFERENCES \"Order\" (\"Order ID\")";
          stat.execute(sql);
      }
      stat.close();
      conn.close();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
  
}
