CREATE TABLE Admin (
  AdminID  integer GENERATED BY DEFAULT AS IDENTITY, 
  Password varchar(20) NOT NULL, 
  PRIMARY KEY (AdminID));
CREATE TABLE Category (
  CatNo integer GENERATED BY DEFAULT AS IDENTITY, 
  Name  varchar(20) NOT NULL, 
  PRIMARY KEY (CatNo));
CREATE TABLE Client (
  ClientID integer GENERATED BY DEFAULT AS IDENTITY, 
  Password varchar(20) NOT NULL, 
  Name     varchar(20) NOT NULL, 
  Phone    integer NOT NULL, 
  Address  varchar(50) NOT NULL, 
  Verified smallint NOT NULL, 
  Bonus    integer NOT NULL, 
  PRIMARY KEY (ClientID));
CREATE TABLE Gift (
  GiftNo      integer GENERATED BY DEFAULT AS IDENTITY, 
  Point       integer NOT NULL, 
  Name        varchar(20) NOT NULL, 
  Description varchar(255), 
  PRIMARY KEY (GiftNo));
CREATE TABLE Orders (
  OrdNo    integer GENERATED BY DEFAULT AS IDENTITY, 
  Amount   integer NOT NULL, 
  Time     bigint NOT NULL, 
  Status   varchar(10) NOT NULL, 
  ClientID integer NOT NULL, 
  PRIMARY KEY (OrdNo));
CREATE TABLE Product (
  ProdNo      integer GENERATED BY DEFAULT AS IDENTITY, 
  Name        varchar(20) NOT NULL, 
  Price       integer NOT NULL, 
  Description varchar(255), 
  CatNo       integer NOT NULL, 
  Brand       varchar(20) NOT NULL, 
  PRIMARY KEY (ProdNo));
CREATE TABLE Product_Orders (
  Quantity integer NOT NULL, 
  ProdNo   integer NOT NULL, 
  OrdNo    integer NOT NULL);
ALTER TABLE Product_Orders ADD CONSTRAINT FKProduct_Or79800 FOREIGN KEY (OrdNo) REFERENCES Orders (OrdNo);
ALTER TABLE Product_Orders ADD CONSTRAINT FKProduct_Or641194 FOREIGN KEY (ProdNo) REFERENCES Product (ProdNo);
ALTER TABLE Orders ADD CONSTRAINT FKOrders325878 FOREIGN KEY (ClientID) REFERENCES Client (ClientID);
ALTER TABLE Product ADD CONSTRAINT FKProduct95323 FOREIGN KEY (CatNo) REFERENCES Category (CatNo);
